apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Performing cleanup..."
        rm -rf /workspace/output/*
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  steps:
    - name: run-tests
      image: python:3.9-slim
      script: |
        python -m pip install --upgrade pip
        pip install nose
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
